# Gradle Properties
org.gradle.jvmargs=-Xmx6G
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel.only-on-demand=true

# Fabric Basic Properties
# https://fabricmc.net/develop/
loader_version=0.19.3

# Mod Properties
mod_archives_base_name  =quickshulker
mod_id                  =quickshulker
mod_license             =MIT
mod_maven_group         =net.kyrptonaught.quickshulker
mod_name                =Quick Shulker Multi
mod_version             =3.2.7

# Global Dependencies
# https://github.com/Fallen-Breath/conditional-mixin
conditionalmixin_version=0.6.4
