# Fabric Properties
# check these on https://fallen-breath.github.io/fabric-versions/?version=26.3-snapshot-5
minecraft_version=26.3-snapshot-5
# Fabric Mod Metadata
minecraft_dependency=>26.2 <=26.3
# Build Information
# The target mc versions for the mod during mod publishing, separated with \n
game_versions=26.3-snapshot-5
# Dependencies
fabric_api_version=0.155.3+26.3
modmenu_version=20.0.1
modmenu_dev_version=0f60900cc2